# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

# Install system dependencies
RUN apk add --no-cache gcc musl-dev linux-headers

# Set working directory
WORKDIR /app

# Copy all files
COPY . /app

# Install Python dependencies
RUN pip install --upgrade pip \
  && pip install --no-cache-dir .

# Expose port 8081 for HTTP transport
EXPOSE 8081

# Set default environment variable for HTTP transport
ENV TRANSPORT=http
ENV PORT=8081

# Run the MCP server
CMD ["python", "-m", "wuwa_mcp_server.server"]
